version: "3.9"

services:
  backend:
    build: .
    container_name: speezup-backend
    env_file:
      - .env
    ports:
      - "4000:4000"
    depends_on:
      - redis
      - db
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: speezup-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    restart: unless-stopped

  db:
    image: postgres:16-alpine
    container_name: speezup-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: speezup
      DATABASE_URL: postgresql://postgres:password@db:5432/speezup

    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  redis-data:
  pgdata:
